PTD_lesson04/Models/PtdCustomer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PTD_lesson04.Models
{
    public class PtdCustomer
    {
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public int YearOfBirth { get; set; }
    }
}

PTD_lesson04/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PTD_lesson04.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PTD_lesson04/Controllers/PtdCustomerController.cs
using PTD_lesson04.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PTD_lesson04.Controllers
{
    public class PtdCustomerController : Controller
    {
        // GET: PtdCustomer
        public ActionResult Index()
        {
            return View();
        }
        // Action: PtdCustomerDetail
        public ActionResult PtdCustomerDetail()
        {
            // tao doi tuong du lieu
            var customer = new PtdCustomer()
            {
                CustomerId = 1,
                FirstName = "Pham Thanh",
                LastName = "Dat",
                Address = "K22CNT3",
                YearOfBirth = 2004
            };
            ViewBag.customer = customer;

            return View();
        }
        //GET: PtdListCustomer
        public ActionResult PtdListCustomer()
        {
            var list = new List<PtdCustomer>()
            {
               new PtdCustomer()
               {
                   CustomerId = 1,
                FirstName = "Pham Thanh",
                LastName = "Dat",
                Address = "K22CNT3",
                YearOfBirth = 2004
               },
               new PtdCustomer()
               {
                   CustomerId=2,
                   FirstName=" Tran Anh",
                   LastName="Sang",
                   Address = "K22CNT3",
                YearOfBirth = 2004
               },
               new PtdCustomer()
               {
                   CustomerId=3,
                   FirstName=" Tran Anh",
                   LastName="Sang",
                   Address = "K22CNT3",
                YearOfBirth = 2004
               },
               new PtdCustomer()
               {
                   CustomerId=4,
                   FirstName=" Tran Anh",
                   LastName="Sang",
                   Address = "K22CNT3",
                YearOfBirth = 2004
               },
            };
            ViewBag.list = list; // Dua ra view bang doi tuong viewBag

            return View();
        }
    }
}

PTD_lesson04/Controllers/PtdCustomerScaffdingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PTD_lesson04.Models;  // Ensure this namespace matches where PtdCustomer is defined

namespace PTD_lesson04.Controllers
{
    public class PtdCustomerScaffoldingController : Controller
    {
        // Mock data
        private List<PtdCustomer> listCustomer = new List<PtdCustomer>()
        {
            new PtdCustomer()
            {
                CustomerId = 1,
                FirstName = "Pham Thanh",
                LastName = "Dat",
                Address = "K22CNT3",
                YearOfBirth = 2004
            },
            new PtdCustomer()
            {
                CustomerId = 2,
                FirstName = "Tran Anh",
                LastName = "Sang",
                Address = "K22CNT3",
                YearOfBirth = 2004
            },
            new PtdCustomer()
            {
                CustomerId = 3,
                FirstName = "Tran Anh",
                LastName = "Sang",
                Address = "K22CNT3",
                YearOfBirth = 2004
            },
            new PtdCustomer()
            {
                CustomerId = 4,
                FirstName = "Tran Anh",
                LastName = "Sang",
                Address = "K22CNT3",
                YearOfBirth = 2004
            }
        };

        // GET: PtdCustomerScaffolding
        //listcustomer
        public ActionResult Index()
        {
            return View(listCustomer);
        }
        [HttpGet]
        public ActionResult PtdCreate()
        {
            var model = new PtdCustomer();
            return View(model);
        }
        [HttpPost]
        public ActionResult PtdCreate(PtdCustomer model)
        {
            //them moi doi tuong khach hang vao ds du lieu
            listCustomer.Add(model);
            //return View(model);
            // chuyen ve trang danh sach
            return RedirectToAction("Index");
        }
        public ActionResult PtdEdit(int id)
        {
            var customer = listCustomer.FirstOrDefault(x=>x.CustomerId==id);
            return View();
        }
    }
}

PTD_lesson04/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PTD_lesson04/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PTD_lesson04/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PTD_lesson04/Views/PtdCustomer/PtdCustomerDetail.cshtml
@{
    ViewBag.Title = "Thong tin khach hang";
}

<div class="alert alert-danger">
    <p> Ma so: @ViewBag.customer.CustomerId</p>
    <p> Ho va Ten: @ViewBag.customer.FirstName @ViewBag.customer.LastName</p>
    <p> Ma so: @ViewBag.customer.Address</p>
    <p> Ma so: @ViewBag.customer.YearOfBirth</p>
</div>

PTD_lesson04/Views/PtdCustomer/PtdListCustomer.cshtml
@{
    ViewBag.Title = "Danh sach khach hang";
    //var list = ViewBag.list;
    var list = Model as List<PTD_lesson04.Models.PtdCustomer>;
    int stt = 0;
}

<h2>Danh sach khach hang</h2>
<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Ma so</th>
                <th> Ho va Ten</th>
                <th>Dia Chi</th>
                <th>Nam sinh</th>
                <th>Chuc Nang</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in list)
            {
                stt++;
                <tr>
                    <td>@stt</td>
                    <td>@item.CustomerId</td>
                    <td>@item.FirstName @item.LastName</td>
                    <td>@item.Address</td>
                    <td>@item.YearOfBirth </td>
                    <td>
                        <a href="#">Edit</a>
                        <a href="#">Delete</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

PTD_lesson04/Views/PtdCustomerScaffolding/Index.cshtml
@model IEnumerable<PTD_lesson04.Models.PtdCustomer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "PtdCreate")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfBirth)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfBirth)
        </td>
        <td>
            @Html.ActionLink("Edit", "PtdEdit", new { id=item.CustomerId }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

PTD_lesson04/Views/PtdCustomerScaffolding/PtdCreate.cshtml
@model PTD_lesson04.Models.PtdCustomer

@{
    ViewBag.Title = "PtdCreate";
}

<h2>PtdCreate</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PtdCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTD_lesson04/Views/PtdCustomerScaffolding/PtdEdit.cshtml
@model PTD_lesson04.Models.PtdCustomer

@{
    ViewBag.Title = "PtdEdit";
}

<h2>PtdEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PtdCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTD_lesson04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Customer Detaill", "PtdCustomerDetail", "PtdCustomer")</li>
                    <li>@Html.ActionLink("List Customers", "PtdCustomerDetail", "PtdCustomer")</li>
                    <li>@Html.ActionLink("List Customers Scaffolding", "index", "PtdCustomerScaffolding")</li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>